import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./components/layout/website";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='bg-gradient-to-t from-bg-gradientTwo to-bg-gradientOne mt-0'
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
